server:
  port: 8081
spring:
  application:
    name: eureka-client1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   #\u914D\u7F6E\u670D\u52A1\u6CE8\u518C\u7684\u5730\u5740