node{
            stage('checkout'){
                    git branch: 'config-server', url: 'https://github.com/hand-wanggang/erueka-demo.git'
            }
            stage('build') {
                    dir('eureka-server1'){
                        echo 'Building'
                        sh "ls -l"
                        sh "gradle clean bootRepackage"
                        sh "docker build -t jenkins/eureka-server-v-1 ."
                    }
            }
            stage('deploy'){
                sh "docker run -d -p 8761:8761 jenkins/eureka-server-v-1"
            }
 }