server:
  port: 8092
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    ser-pro:
      path: /server-pro/**          # \u5982\u679C\u5339\u914D\u5730\u5740\u6210\u529F\u5219\u8F6C\u53D1\u5230 service-provide \u670D\u52A1
      serviceId: service-provide
    ser-cus:
      path: /server-cus/**          # \u5982\u679C\u5339\u914D\u5730\u5740\u6210\u529F\u5219\u8F6C\u53D1\u5230 server-cus \u670D\u52A1
      serviceId: service-customer