server:
  port: 8889
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hand-wanggang/CloudConfig # git 仓库地址
          #password:  #git 仓库密码
          #username:  #git 密码
          search-paths: '{profile}' # 查找路径
        bootstrap: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/